pipeline {
    agent any
    tools {
        maven 'mvn'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
            post {
				success {
					archiveArtifacts 'target/*.jar'
                    nexusArtifactUploader artifacts: [
						[
							artifactId: 'my-app', 
							file: 'target/*.jar', 
							type: 'jar'
						]
					], 
					credentialsId: 'nexus-password', 
					groupId: 'com.mycompany.app', 
					nexusUrl: '10.95.0.2:8081', 
					nexusVersion: 'nexus3', 
					protocol: 'http', 
					repository: 'maven-snapshots', 
					version: '1.0-SNAPSHOT'
				}
			}
        }
        stage('Test') {
           
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        /*stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }*/
        stage('Docker Build') {
            steps {
                sh 'ls -la'
                sh 'docker build -t ahmedatefosman/simple-app:${BUILD_ID} .'
            }
        }
        stage('Docker push') {
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'atef-dockerhub-passwd',
                            	 usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
				    sh 'docker login -u ${USERNAME}  -p ${PASSWORD} '
                    sh 'docker push ahmedatefosman/simple-app:${BUILD_ID}'
				}
            }
        }
        stage('Deliver') {
            steps {
                sh 'docker run ahmedatefosman/simple-app:${BUILD_ID}'
            }
        }
    }
}
