pipeline {
    agent any
    tools {
        maven 'mvn'
    }
    stages {
        stage('Build') {
            /*agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v cashe-m2:/root/.m2'
                }
            }*/
            steps {
                //withMaven(mavenLocalRepo: ' ~/.m2/repository ') {
                    sh 'mvn -B -DskipTests clean package'
                //}
            }
            post {
				success {
					archiveArtifacts 'target/*.jar'
				}
			}
        }
        stage('Test') {
            /*agent {
                docker {
                    image 'maven:3-alpine'
                    args '-v cashe-m2:/root/.m2'
                }
            }*/
            steps {
                //withMaven(mavenLocalRepo: ' ~/.m2/repository ') {
                    sh 'mvn test'
                //}
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        /*stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }*/
        stage('Docker Build') {
            steps {
                sh 'ls -la'
                sh 'docker build -t ahmedatefosman/simple-app:${BUILD_ID} .'
            }
        }
        stage('Docker push') {
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'atef-dockerhub-passwd',
                            	 usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
				    sh 'docker login -u ${USERNAME}  -p ${PASSWORD} '
                    sh 'docker push ahmedatefosman/simple-app:${BUILD_ID}'
				}
            }
        }
        stage('Deliver') {
            steps {
                sh 'docker run ahmedatefosman/simple-app:${BUILD_ID}'
            }
        }
    }
}
