pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        /*stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }*/
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t ahmedatefosman/simple-app:${BUILD_ID}  -f jenkins/scripts/Dockerfile .'
            }
        }
        stage('Build') {
            steps {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'atef-dockerhub-passwd',
                            	 usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
				    sh 'docker login -u ${env.USERNAME}  -p ${env.PASSWORD} '
				}
                sh 'docker push ahmedatefosman/simple-app:${BUILD_ID}'
            }
        }
        stage('Deliver') {
            steps {
                sh 'docker run ahmedatefosman/simple-app:${BUILD_ID}'
            }
        }
    }
}
